version: '3'

services:
  img:
    build: .
    container_name: gotether
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: gotether
      MYSQL_USER: root
      MYSQL_PASSWORD: